name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.4.17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4969e3fcd00a36d75b44562d5e66f658e2d5d3b1521dcb54457f40842a15c04"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
