name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.4.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59c2c90a7a7826ca6a32882686287d59e24f748b0ecefe83640946db41c3b54a"

[versions]
fabric = "0.16.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
