name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.4.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d667ab476025b0cd71fcf923496c2061f19e97e4a5dc4f6198c28ae285a4065d"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
