name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.4.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddd2f88aedf3b6263da279f03564ad8e1fd21317160f9d623c7e4afde8303c28"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
