name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.4.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c83694441c52b008feb6057ea34127d1f0fb5194d2b80abf241171849ab96bb"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21"]
