name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.4.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b966927d91c284e80460406a7f8763f3d727deac6c1c5b815ff34487959a77b7"

[versions]
fabric = "0.16.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
