name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.4.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83c755b28f087274645675141a9bd50e805c85778118b6d0af57a432b4d698e1"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
