name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.4.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "609cca9daa65128c4c04e4dd5f9a26b526c1bc8f8dea7572b3960b4d13d10af4"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
