name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.4.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08c523f9014c923c5234fd6e62751623fb059601f41d8113b0771067ab03544c"

[versions]
fabric = "0.16.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
