name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.4.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a66b48916f37af2b35b6d703ee2285659e95bfaa959eb73042f7e3be1d46c212"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
